### ISSUE TITLE
Migration is broken

### ISSUE THREAD

**Issue by jamstooks** [AASHE/iss#16]
There was a bug in the migration code that referenced `alpha2` instead of `alpha_2`. On top of that, Scott's comment about that migration:

> this doesn't fully work

implies to me that it should probably be rolled back while we think the right solution to the issue. I can confirm that, as the migration crashes for me:

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "iss_countrycode_country_name_key"
DETAIL:  Key (country_name)=(Aruba) already exists.
```

I created a release, [v2.4](https://github.com/AASHE/iss/releases/tag/v2.4) to use in dependent projects in the interim.

**Comment by rerb** [comment]
This can be closed, correct, Ben?

**Comment by jamstooks** [comment]
Yep.
